### ISSUE TITLE
Make cars just suggestions - not instances. 

### ISSUE THREAD

**Issue by MartyFibghtov** [MartyFibghtov/kernel-housing#37]
Car and its number should be just suggestion for faster filling. 

So the data should only be saved once. 

Car type, mark, number should be fields in EntranceRequests. 

Reason: 
We don't fill full numbers of cars so there might be collisions and its better to do it simpler.

# Tasks
- [x] Redefine schema of the DB so that it implies new logic 
- [x] Fix address suggestions functionality 
- [x] Create ability to update car info in created requests on back
    - [x] On front 
- [ ] #39

- [ ] #40
